#!/bin/bash

set -e

rm -rf Release

mv config.json config1.json 
mv releaseconfig.json config.json 

./makedeb
dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained=true -p:GenerateRuntimeConfigurationFiles=true -p:IncludeNativeLibrariesForSelfExtract=true

mkdir Release

cp -rf bin/Release/net6.0/win-x64/publish/ Release
mv Release/publish Release/SICK_Program_win

zip -r Release/SICK_Program_win.zip Release/SICK_Program_win
rm -rf Release/SICK_Program_win

mv SICK-DEB.deb Release/

mv config.json releaseconfig.json 
mv config1.json config.json 

zip -r Release.zip Release
rm -rf Release

exit 0
